// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleEFCorePlus.Models;

#nullable disable

namespace SampleEFCorePlus.Migrations
{
    [DbContext(typeof(FooContext))]
    partial class FooContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("SampleEFCorePlus.Models.Bar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FooBarId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FooBarId");

                    b.ToTable("Bars");
                });

            modelBuilder.Entity("SampleEFCorePlus.Models.Foo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BarId");

                    b.ToTable("Foos");
                });

            modelBuilder.Entity("SampleEFCorePlus.Models.FooBar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FooBars");
                });

            modelBuilder.Entity("SampleEFCorePlus.Models.Bar", b =>
                {
                    b.HasOne("SampleEFCorePlus.Models.FooBar", "FooBar")
                        .WithMany()
                        .HasForeignKey("FooBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FooBar");
                });

            modelBuilder.Entity("SampleEFCorePlus.Models.Foo", b =>
                {
                    b.HasOne("SampleEFCorePlus.Models.Bar", "Bar")
                        .WithMany()
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bar");
                });
#pragma warning restore 612, 618
        }
    }
}
